name: 手动Beta构建
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 分支名称
        required: true
        type: string
        default: develop
jobs:
  build:
    name: 触发 Beta Build
    permissions:
      contents: write
    uses: ./.github/workflows/Build.yml
    with:
      branch: ${{ inputs.branch }}
      build_mode: "beta"
