name: 手动Beta构建
on:
  workflow_dispatch:
jobs:
  build:
    name: 触发 Beta Build
    permissions:
      contents: write
    uses: ./.github/workflows/Build.yml
    with:
      branch: ${{ github.ref_name }}
      build_mode: "beta"
