name: 每日构建
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    name: Nightly Build
    runs-on: windows-latest
    steps:
      # 准备环境
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: setup build env
        uses: ./.github/workflows/Setup Build Env.yml
      # 数据处理
      - name: set loglevel
        run: node .github/scripts/processLoglevelToTrace.js
      # Build
      - name: Build
        run: pnpm --filter @techclass/app tauri build
      - name: Rename artifact
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyyMMdd"
          $hash = git rev-parse --short HEAD
          $sourcePath = Get-ChildItem -Path "App/src-tauri/target/release/bundle/nsis" -File | Select-Object -First 1
          $newName = "Techclass-nightly-${date}-${hash}$($sourcePath.Extension)"
          $uploadName = "Techclass-nightly-${date}-${hash}"
          Rename-Item -Path $sourcePath.FullName -NewName $newName
          "ARTIFACT_NAME=$uploadName" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: App/src-tauri/target/release/bundle/nsis/*
          retention-days: 30
