name: 设置构建环境
description: 设置构建环境
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: "pnpm"

    - name: install dependencies
      run: pnpm install
      shell: bash

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: "./App/src-tauri -> target"